services:
  memcached:
    image: bitnami/memcached:latest
    ports:
      - "11211:11211"
  cms-mongo:
    image: mongo:latest
    ports:
        - '27017:27017'
    container_name: cms-mongo
    restart: always
    logging:
        options:
            max-size: 1g
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=5
      -c max_wal_senders=5
    ports:
      - "5432:5432"

  redpanda:
    profiles:
      - donotstart
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 512M
      --reserve-memory 0M
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092,PLAINTEXT_HOST://127.0.0.1:29092
    ports:
      - "9092:9092"
      - "29092:29092"   # for host access
      - "9644:9644"   # Admin API

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  debezium:
    profiles:
      - donotstart
    image: debezium/connect:2.6
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_status
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redpanda